dataset:
  #files: '/glade/work/kavulich/MPAS/tutorial/120km_global/rundir/diag.2025-05-0*nc'
  files: '/glade/derecho/scratch/gallus/dtc_mpas/expt_dirs/1km_hrrrIC/Texas_test/mpas_atm/2020081000/ens_1_KF/diag.2020-08-10_0[0-1].nc'
  #gridfile: '/glade/work/kavulich/MPAS/tutorial/120km_global/rundir/x1.40962.init.nc'
  gridfile: '/glade/derecho/scratch/gallus/dtc_mpas/expt_dirs/1km_hrrrIC/Texas_test/mpas_atm/2020081000/ens_1_KF/history.2020-08-10_00.00.00.nc'
  vars:
    t2m:
      source: native
      plot:
        lakes:
          scale: '10m'
          enable: False
          color: 'lightblue'
    delta_t2m:
      source: derived
      function: diff_prev_timestep
      inputs:
        - "t2m"
      attrs:
        long_name: "1-hour change in 2m temperature"
        units: "K"
      plot:
        proj:
          colormap: seismic
    t_isobaric:
      source: native
      lev: all
      vertcoord: nIsoLevelsT
      plot:
        edges:
          color: face
          width: 0.1
    precipw:
      source: native
    rainnc:
      source: native
    rain_1hr:
      source: derived
      function: diff_prev_timestep
      inputs:
        - "rainnc"
      attrs:
        long_name: "1-hour total grid-scale precipitation"
        units: "mm"
    refl10cm_1km:
      source: native
      plot:
        colormap: radar_refl
        dpi: 600

plot:
  # {var} = Variable name
  # {lev} = Variable level
  # {varln} = Variable "long name" (not recommended for filenames since these often contain spaces)
  # {units} = Variable units
  # {filename} = Name of file being read for plotted data
  # {fnme} = Name of file (minus extension) being read for plotted data
  # {date} = The date of plotted data, in %Y-%m-%d format
  # {time} = The time of plotted data, in %H:%M:%S format

  filename: 'custom_plot/{var}_lev{lev}_{date}_{time}.png'
  title:
    text: 'Plot of {varln}, level {lev} for MPAS forecast, {date} {time}'
    fontsize: 8
  edges:
    #    color: black
    color: face
    # set width to 0 to have no borders
    width: 0.1
  boundaries:
    detail: 2
    scale: '10m'
    color: ['k','gray','lightgray']
    linewidth: [1,0.5,0.2]

  coastlines:
    scale: '10m'
    color: 'k'
    linewidth: 0.2
  colorbar:
    orientation: vertical
    label: 'Units: {units}'
    fontsize: 8
  # Colormap for output from Matplotlib. Reference: https://matplotlib.org/stable/gallery/color/colormap_reference.html
  colormap: "viridis"
  dpi: 300
  figwidth: 5
  projection:
    projection: PlateCarree
