name: mpas_plot
channels:
  - conda-forge
  - anaconda
  - ufs-community
  - defaults
dependencies:
  - numpy=1.26*
  - matplotlib
  - netcdf4
  - xarray=2025.9.0
  - cartopy
  - uwtools=2.9*
  - uxarray=2025.05*
