name: mpas_plot
channels:
  - conda-forge
  - anaconda
  - ufs-community
  - defaults
dependencies:
  - numpy
  - matplotlib
  - netcdf4
  - cartopy
  - uwtools=2.9*
  - xarray=2026.04
  - uxarray=2026.04.1
