# To regenerate conda-lock.yml after changes: mamba install -n base conda-lock && conda-lock -f environment.yml -p linux-64 -p osx-arm64 -p linux-aarch64
name: mpas_plot
channels:
  - conda-forge
  - anaconda
  - ufs-community
  - defaults
dependencies:
  - numpy
  - matplotlib
  - netcdf4
  - cartopy
  - uwtools=2.9*
  - xarray=2026.04
  - uxarray=2026.04.1
