name: mpas_plot
channels:
  - conda-forge
  - anaconda
  - ufs-community
  - defaults
dependencies:
  - numpy
  - matplotlib
  - netcdf4
  - cartopy
  - uwtools=2.9*
  - xarray=2025.11*
  - uxarray=2025.11*
